package com.xworkz.engineers.engineer;

import com.xworkz.engineers.engineer.constants.Branch;

public class EEEEngineer extends Engineer{
	private Branch branch=Branch.EEE;
	
	
	public void powerGenerate()
	{
		System.out.println("********************");
		System.out.println("Power generated");
		System.out.println("Power generated by"+this.branch);
		
		
		
	}
	/**
	 * getParentBranch() method used to access the parent branch which child class Extends
	 * @return
	 */
	public Branch getParentBranch()
	{
		return super.getBranch();
	}

	public Branch getBranch() {
		return branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}
	

}
